from_latest_tag = false
ignore_merge_commits = false
disable_changelog = true
disable_bump_commit = true
generate_mono_repository_global_tag = true
branch_whitelist = []
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = []
post_bump_hooks = [
    "git push --tags",
]
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks]

[commit_types]

[changelog]
path = "CHANGELOG.md"
authors = []

[bump_profiles]

[packages]
efficient-coding = { path = "efficient-coding" }
robust-testing = { path = "robust-testing" }
seamless-integration = { path = "seamless-integration" }
