name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  cocogitto:
    name: Cocogitto
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: cocogitto
        uses: cocogitto/cocogitto-action@v3
        with:
          release: "true"
          git-user: github-actions[bot]
          git-user-email: github-actions[bot]@users.noreply.github.com
